#!/bin/bash
# Generate the static js file

SOURCE_FILES="
ui.js
ws.js
index.js
"

ROOT="$(dirname $0)"
OUTPUT="$ROOT/www/static/v1.js"

echo "// This file is generated by gen_js.sh (do not modify)" > $OUTPUT

echo "GENERATING JS FILES..."
for file in $SOURCE_FILES ; do
  file="$ROOT/js/$file"
  echo "merging $file"
  echo "/* == $file == */" >> $OUTPUT
  cat $file >> $OUTPUT
done

if [[ "$1" == "--git-add" ]] ; then
  echo "Adding generated files to git"
  git add smppgc/www/static/v1.js
fi
echo "done"
