[default]
max_stored_messages=30
name_reserve_time=1209600 # 2 weeks
max_users=0
port = 8081

[debug]
static_dir="www/static"
template_dir="www/templates"
address = "127.0.0.1"
log_level="normal"

[release]
static_dir="/var/www/static"
template_dir="/var/www/templates"
address = "0.0.0.0"
log_level = "critical"

