[default]
max_stored_messages=30
max_reserved_names=2
max_users=1000
port = 8081
offline=false

[default.rate_limit]
min_message_time_soft=400
min_message_time_hard=50
kick_burst=1000

[debug]
static_dir="www/static"
template_dir="www/templates"
address = "127.0.0.1"
log_level="normal"

[debug.databases.sqlx]
url="postgres://ldev@localhost/smppgc_debug"


[release]
static_dir="/var/smppgc/www/static"
template_dir="/var/smppgc/www/templates"
address = "127.0.0.1"
log_level = "critical"

[release.databases.sqlx]
url="postgres://www@localhost/smppgc_prod"
