[default]
max_stored_messages=30
max_reserved_names=2
max_users=1000
max_username_len=30
max_message_len=150
port = 8080
offline=false

min_message_time_soft=400
min_message_time_hard=50
kick_burst=1000

[debug]
static_dir="www/static"
template_dir="www/templates"
address = "0.0.0.0"
log_level="normal"

[release]
static_dir="/var/smppgc/www/static"
template_dir="/var/smppgc/www/templates"
address = "127.0.0.1"
log_level = "critical"

